# configurations
dataset_cfg:
    OfficeHome:
        name: OfficeHome
        path: /home/xxx/data/OfficeHome
        text_path: /home/xxx/data/OfficeHome/text
        num_classes: 65
        domains:
                - Art
                - Clipart
                - Product
                - RealWorld
        list:
          all: all.txt
            1shot:
                train: train_1.txt
                test: test_1.txt
            3shot:
                train: train_3.txt
                test: test_3.txt
            val: val.txt
    Office31:
        name: Office31
        path: /home/xxx/data/Office31
        text_path: /home/xxx/data/Office31/text
        num_classes: 31
        domains:
                - amazon
                - dslr
                - webcam
        list:
            all: all.txt
            1shot:
                train: train_1.txt
                test: test_1.txt
            3shot:
                train: train_3.txt
                test: test_3.txt
            val: val.txt
    DomainNet:
        name: DomainNet
        path: /home/xxx/data/DomainNet
        text_path: /home/xxx/data/DomainNet/text
        num_classes: 126
        domains:
                - clipart
                - painting
                - real
                - sketch
        list:
            all: all.txt
            1shot:
                train: train_1.txt
                test: test_1.txt
            3shot:
                train: train_3.txt
                test: test_3.txt
            val: val.txt
